name: Update Quotes DB

permissions:
  contents: write  # permite push no repositório

on:
  schedule:
    - cron: "*/2 * * * *"  # a cada 30 minutos
  workflow_dispatch:        # também pode rodar manualmente

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install requests

      - name: Run update script
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
        run: python main.py

      - name: Commit and push updated DB
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add historico.db
          git commit -m "Update historico.db [skip ci]" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
